name: Tests
on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.0-noble
    steps:
      - name: Install dependencies
        run: apt update && apt install -y unzip

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test:storybook --run

      - name: Run linting
        run: bun run lint

      - name: Build Storybook
        run: bun run build-storybook -o storybook-static